services:
#Объявление сервисов
  flask-app:
    build: ./ #Запуск Dockerfile из текущей директории
    container_name: flask-app-1
    ports:
      - "5000:5000" #Выводим порты наружу для подключения внешний/внутренний парт контейнера
    depends_on: #Определяем порядок запуска, после другого приложения
      - redis 

  redis:
    image: redis:alpine #Задаётся образ,который будет использоваться
    container_name: redis
    ports:
      - "6379:6379"
